require 'fileutils'

file "ruby" do
  FileUtils.ln_s '../ruby', 'ruby'
end

file "Joyau.prx" do
  FileUtils.ln_s '../Joyau.prx', 'Joyau.prx'
end

task :tests => ["ruby", "Joyau.prx"] do
  IO.popen("pspsh", 'w+') do |pipe|
    trap('INT') do
      pipe.puts "reset"
    end

    pipe.puts "./Joyau.prx"
    
    line = ''
    puts line while line = pipe.gets

    ipe.puts "reset"
  end
end

task :default => [:tests]
