require 'fileutils'

file "ruby" do
  FileUtils.ln_s '../ruby', 'ruby'
end

file "Joyau.prx" do
  FileUtils.ln_s '../Joyau.prx', 'Joyau.prx'
end

task :tests => ["ruby", "Joyau.prx"] do
  trap('INT') { system "pspsh -e reset" }

  IO.popen("pspsh", 'w+') do |pipe|
    pipe.puts "./Joyau.prx"
    
    line = ''
    puts line while line = pipe.gets
  end
end

task :default => [:tests]
